<?php

return [
    'allowed_data_models' => [
        'about',
        'contactus',
        'category',
        'lang',
        'slider',
        'industry',
        'maincontact',
        'social',
        'ourteam',
        'client',
        'ourwork',
        'feedback',
        'achivement',
        'service',
        'page',
        'setting',
        'contact',
        'option',
        'metasetting',
        'des',
        'specification',
        'certificate',
        'faq',
        'blog',
        'mediaimage',
        'mediavideo',
        'coupon',
        'event',
    ],
];
